### PR TITLE
Milestone: Connect to API

### PR DESCRIPTION
**Pull request by newhorizon-tech**
Made use of: 

- Thunks
- Middleware
- API

### CODE REVIEW

**Review by Ghiftee — CHANGES_REQUESTED** [review]
## STATUS: CHANGES REQUIRED ♻️♻️
Hello 👋🏽 
Good job working on the project so far! 
However, there are some issues that you need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [x] Your project currently uses the wrong linter files, please refer to [React & Redux linters](https://github.com/microverseinc/linters-config/tree/master/react-redux) to set up the correct linters for this project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by Ghiftee** [comment]
Hi @newhorizon-tech your linters are all set up correctly. I apologize for that mistake 🙏🏽 
Please submit your PR for another review.
All the best 💪🏽

**Comment by bellom** [comment]
Hello 👋,

This is an additional review as a result of the second opinion request.

Looks like the issue was resolved here, so I have nothing else to say other than best of luck with the rest of your projects!

The CR will review as normal, kindly wait for her feedback before submitting for another review.

Keep rocking 🚀!

**Review by afanimartin — APPROVED** [review]
Hi @newhorizon-tech, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

### Martin Afani
#### Slack: whiz25

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by rloterh — COMMENTED** [review]
## Status: Approved :heavy_check_mark:

Hi Alaukik,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾 :shipit: . Congratulations!  🎉🌟 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
